version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_Youcode
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Youcode
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_Youcode
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - postgres

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_Youcode
    restart: always
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - postgres
